services:
  sjtu-vpn-ss:
    build: .
    image: sjtu-vpn-ss:latest
    container_name: sjtu-vpn-ss
    restart: unless-stopped

    network_mode: bridge

    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    privileged: true

    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.disable_ipv6: "1"

    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"

    environment:
      JACCOUNT: "SET YOUR JACCOUNT HERE"
      JPASSWORD: "SET YOUR JPASSWORD HERE"
      VPN_SERVER: "stuv4.vpn.sjtu.edu.cn"
      VPN_RIGHTID: "@stu.vpn.sjtu.edu.cn"

      SS_ADDR: "0.0.0.0"
      SS_PORT: "8388"
      SS_METHOD: "aes-256-gcm"
      SS_PASSWORD: "SET YOUR PASSWORD HERE"
